env_id: PsyonicThumbEnv-v0
policy: "MlpPolicy"
total_timesteps: 1000000
n_steps_per_update: 2000  # n steps per update
n_epochs: 20
learning_rate: 0.003
ent_coef: 0.01

epi_length: 100
short_epi: False # if True, the episode length is 50

reference_audio: "ref_audio/xylophone/ref_hit1_clip.wav"
# wandb_run_id: None # if we want to continue training from a previous run, provide the run id here
# load_model_path: None # if we want to continue training from a previous model, provide the path here
eval_freq: 2000

psyonic:
    initial_state: [50, 70 , 110, 115, 50, -20]
    max_degree: -10
    min_degree: -50

reward_weight:
    amplitude_step: 1
    movement: 0.005
    amplitude: 10
    hitting_times: 10
    onset_shape: 10
    hitting_timing: 40
