env_id: PsyonicThumbEnv-v0
policy: "MlpPolicy"
total_timesteps: 3000000
n_steps_per_update: 1000  # n steps per update
n_epochs: 20

epi_length: 100
reference_audio: "ref_audio/xylophone/ref_hit1_clip.wav"
# wandb_run_id: None # if we want to continue training from a previous run, provide the run id here
# load_model_path: None # if we want to continue training from a previous model, provide the path here
eval_freq: 5000

psyonic:
    initial_state: [50, 70 , 110, 115, 50, -30]
    max_degree: -10
    min_degree: -50

reward_weight:
    movement: 3
    amplitude: 10
    hitting_times: 10
    onset_shape: 10
    hitting_timing: 50
